using System;

namespace FacturacionCFDI.Datos.Polizas
{
    public class RUE
    {
        public string Sistema { get; set; }
        public DateTime FechaEmision { get; set; }
        public int AmarreOrden { get; set; }
        public string Poliza { get; set; }
        public string CT { get; set; }
        public DateTime FechaInicio { get; set; }
        public DateTime FechaTermino { get; set; }
        public string Endoso { get; set; }
        public DateTime FechaIniEndoso { get; set; }
        public DateTime FechaFinEndoso { get; set; }
        public string CausaEndoso { get; set; }
        public string Cod_Ramo { get; set; }
        public string Des_Ramo { get; set; }
        public string SubRamo { get; set; }
        public string Cod_Ramocnsf { get; set; }
        public string Desc_Ramocnsf { get; set; }
        public string Cod_Producto { get; set; }
        public string Producto { get; set; }
        public string Cod_Plan { get; set; }
        public string Plan { get; set; }
        public decimal PrimaNeta { get; set; }
        public decimal Financiamiento { get; set; }
        public decimal Gasto { get; set; }
        public decimal Iva { get; set; }
        public DateTime FechaContable { get; set; }
        public string Cod_Oficina { get; set; }
        public string Oficina { get; set; }
        public string Zona { get; set; }
        public string Cve_Agente { get; set; }
        public string Agente { get; set; }
        public string Cve_Supervisor { get; set; }
        public string Supervisor { get; set; }
        public string Cod_Contratante { get; set; }
        public string Contratante { get; set; }
        public string TipoPersona_Cont { get; set; }
        public string Rfc_Cont { get; set; }
        public DateTime FechaNacimiento_Cont { get; set; }
        public string Sexo_Cont { get; set; }
        public string PaisNacimiento_Cont { get; set; }
        public string IdentificacionPersonal { get; set; }
        public string Nacionalidad_Cont { get; set; }
        public string Residencia_Cont { get; set; }
        public string Domicilio_Cont { get; set; }
        public string NumInterior_Cont { get; set; }
        public string NumExterior_Cont { get; set; }
        public string Colonia_Cont { get; set; }
        public string Estado_Cont { get; set; }
        public string Municipio_Cont { get; set; }
        public string CodigoPostal_Cont { get; set; }
        public string ComprobanteDomicilio { get; set; }
        public string Ocupacion_Cont { get; set; }
        public string Telefono_Cont { get; set; }
        public string Correo_Cont { get; set; }
        public string Giro_Mercantil { get; set; }
        public string Fecha_Constitucion { get; set; }
        public string Folio_Mercantil { get; set; }
        public string Nombre_Apoderado { get; set; }
        public string Politicamente_Expuesto { get; set; }
        public string Cod_Asegurado { get; set; }
        public string Asegurado { get; set; }
        public int Orden { get; set; }
        public int Inciso { get; set; }
        public DateTime FechaIniAsegurado { get; set; }
        public DateTime FechaFinAsegurado { get; set; }
        public string ParentesCoase { get; set; }
        public string EstatusAsegurado { get; set; }
        public decimal PNeta_Ase { get; set; }
        public DateTime AntReconocida { get; set; }
        public DateTime AntPlanSeguro { get; set; }
        public string Tipopersona_Ase { get; set; }
        public string Rfc_Ase { get; set; }
        public DateTime FechaNacimiento_Ase { get; set; }
        public string Sexo_Ase { get; set; }
        public string PaisNacimiento_Ase { get; set; }
        public string Nacionalidad_Ase { get; set; }
        public string Residencia_Ase { get; set; }
        public string Domicilio_Ase { get; set; }
        public string NumInterior_Ase { get; set; }
        public string NumExterior_Ase { get; set; }
        public string Colonia_Ase { get; set; }
        public string Estado_Ase { get; set; }
        public string Municipio_Ase { get; set; }
        public string Codigopostal_Ase { get; set; }
        public string Ocupacion_Ase { get; set; }
        public string Telefono_Ase { get; set; }
        public string Correo_Ase { get; set; }
        public string Politicamente_Expuesto_Ase { get; set; }
        public string Cod_Tarifa { get; set; }
        public string Tarifa { get; set; }
        public string Cod_Tecnico { get; set; }
        public string Tecnico { get; set; }
        public string Deducible { get; set; }
        public string SumAsegurada { get; set; }
        public string CoaSeguro { get; set; }
        public string Thq { get; set; }
        public string Cod_Basehosp { get; set; }
        public string BaseHospitalaria { get; set; }
        public string ElimDeducible { get; set; }
        public string Incre_Saparto { get; set; }
        public string TopecoAseguro { get; set; }
        public string AsistenciaDental { get; set; }
        public string AsitenciaFuneraria { get; set; }
        public string EmergenciaExtranjero { get; set; }
        public string CoberturaExtranjero { get; set; }
        public string FichaTecnica { get; set; }
        public string RedCoaNariz { get; set; }
        public string CobVisual { get; set; }
        public string CobDental { get; set; }
        public string Exclusiones { get; set; }
        public string PorExtraPrima { get; set; }
        public string PreExistencia { get; set; }
        public int Ind_Idha { get; set; }
        public int Ind_Can { get; set; }
        public string Idha_Sas { get; set; }
        public string Can_Sas { get; set; }
        public string MonedaContratada { get; set; }
        public int Cod_FormaPago { get; set; }
        public string FormaPago { get; set; }
        public string EstatusPoliza { get; set; }
        public string FechaCancelacion { get; set; }
        public string MotivoCan { get; set; }
        public string TipoPoliza { get; set; }
        public string AutoAdministrada { get; set; }
        public string Pool { get; set; }
        public string Ejecutivo { get; set; }
        public string Zonatencion { get; set; }
        public string Region { get; set; }
        public string Registro_Cnsf_Condusef { get; set; }
        public string Recargo { get; set; }
        public string Siniestros { get; set; }
        public decimal Comisiones { get; set; }
        public decimal Prima_Total { get; set; }
    }
}
